export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const GET_CLEANING_ITEMS = "UPDATE_CLEANING_TYPES";
export const UPDATE_ORDER_ITEMS = "UPDATE_ORDER_ITEMS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_COMPLETED_DATE = "UPDATE_COMPLETED_DATE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_CURRENT_ORDER = "UPDATE_CURRENT_ORDER";
export const SAVE_CURRENT_ORDER = "SAVE_CURRENT_ORDER";

export const SET_STATUSES = "SET_STATUSES";
