export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const UPDATE_ORDER_ITEMS = "UPDATE_ORDER_ITEMS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_COMPLETED_DATE = "UPDATE_COMPLETED_DATE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_CURRENT_ORDER = "UPDATE_CURRENT_ORDER";

export const SET_STATUSES = "SET_STATUSES";
export const SET_CHANGED_STATUSES = "SET_CHANGED_STATUSES";

export const GET_CLEANING_ITEMS = "GET_CLEANING_ITEMS";
export const SET_CLEANING_TYPES = "SET_CLEANING_TYPES";
export const SET_CHANGED_CLEANING_TYPES = "SET_CHANGED_CLEANING_TYPES";
