export const DATA_AVAILABLE = 'DATA_AVAILABLE';
export const SET_CLEANING_TYPES = 'SET_CLEANING_TYPES';
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_CURRENT_ORDER = "UPDATE_CURRENT_ORDER";

